apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: chesty07/udagram-reverseproxy:v2a
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
        ports:
          - containerPort: 8080